### ISSUE TITLE
Add North (Thai highlands Part 1) national parks (19 entries)

### ISSUE THREAD

**Issue by OozyGrub** [OozyGrub/thai-national-park#7]
### Datasource
https://en.wikipedia.org/wiki/List_of_national_parks_of_Thailand

**Comment by burmanp** [comment]
Hi, could you give a bit more details on the contribution guideline? Forking, Branching and PR preferences etc? Thank you.

**Comment by OozyGrub** [comment]
Adding national park entries in `data.json` as shown in [readme](https://github.com/OozyGrub/thai-national-park#readme)
